# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eventlayerdialogbase.ui'
#
# Created: Wed Sep 07 14:59:37 2016
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_EventLayerDialogBase(object):
    def setupUi(self, EventLayerDialogBase):
        EventLayerDialogBase.setObjectName(_fromUtf8("EventLayerDialogBase"))
        EventLayerDialogBase.resize(268, 459)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EventLayerDialogBase.sizePolicy().hasHeightForWidth())
        EventLayerDialogBase.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtGui.QGridLayout(EventLayerDialogBase)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mPointRadioButton = QtGui.QRadioButton(EventLayerDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mPointRadioButton.sizePolicy().hasHeightForWidth())
        self.mPointRadioButton.setSizePolicy(sizePolicy)
        self.mPointRadioButton.setObjectName(_fromUtf8("mPointRadioButton"))
        self.horizontalLayout.addWidget(self.mPointRadioButton)
        spacerItem = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mLineRadioButton = QtGui.QRadioButton(EventLayerDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mLineRadioButton.sizePolicy().hasHeightForWidth())
        self.mLineRadioButton.setSizePolicy(sizePolicy)
        self.mLineRadioButton.setObjectName(_fromUtf8("mLineRadioButton"))
        self.horizontalLayout.addWidget(self.mLineRadioButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.mLineLayeLabel = QtGui.QLabel(EventLayerDialogBase)
        self.mLineLayeLabel.setObjectName(_fromUtf8("mLineLayeLabel"))
        self.gridLayout_3.addWidget(self.mLineLayeLabel, 1, 0, 1, 1)
        self.mLineLayerComboBox = QtGui.QComboBox(EventLayerDialogBase)
        self.mLineLayerComboBox.setObjectName(_fromUtf8("mLineLayerComboBox"))
        self.gridLayout_3.addWidget(self.mLineLayerComboBox, 1, 1, 1, 1)
        self.mLineFieldLabel = QtGui.QLabel(EventLayerDialogBase)
        self.mLineFieldLabel.setObjectName(_fromUtf8("mLineFieldLabel"))
        self.gridLayout_3.addWidget(self.mLineFieldLabel, 2, 0, 1, 1)
        self.mLineFieldComboBox = QtGui.QComboBox(EventLayerDialogBase)
        self.mLineFieldComboBox.setObjectName(_fromUtf8("mLineFieldComboBox"))
        self.gridLayout_3.addWidget(self.mLineFieldComboBox, 2, 1, 1, 1)
        self.mEventLayerLabel = QtGui.QLabel(EventLayerDialogBase)
        self.mEventLayerLabel.setObjectName(_fromUtf8("mEventLayerLabel"))
        self.gridLayout_3.addWidget(self.mEventLayerLabel, 3, 0, 1, 1)
        self.mEventTableComboBox = QtGui.QComboBox(EventLayerDialogBase)
        self.mEventTableComboBox.setObjectName(_fromUtf8("mEventTableComboBox"))
        self.gridLayout_3.addWidget(self.mEventTableComboBox, 3, 1, 1, 1)
        self.mEventFieldLabel = QtGui.QLabel(EventLayerDialogBase)
        self.mEventFieldLabel.setObjectName(_fromUtf8("mEventFieldLabel"))
        self.gridLayout_3.addWidget(self.mEventFieldLabel, 4, 0, 1, 1)
        self.mEventFieldComboBox = QtGui.QComboBox(EventLayerDialogBase)
        self.mEventFieldComboBox.setObjectName(_fromUtf8("mEventFieldComboBox"))
        self.gridLayout_3.addWidget(self.mEventFieldComboBox, 4, 1, 1, 1)
        self.mFromFieldLabel = QtGui.QLabel(EventLayerDialogBase)
        self.mFromFieldLabel.setObjectName(_fromUtf8("mFromFieldLabel"))
        self.gridLayout_3.addWidget(self.mFromFieldLabel, 5, 0, 1, 1)
        self.mFromFieldComboBox = QtGui.QComboBox(EventLayerDialogBase)
        self.mFromFieldComboBox.setObjectName(_fromUtf8("mFromFieldComboBox"))
        self.gridLayout_3.addWidget(self.mFromFieldComboBox, 5, 1, 1, 1)
        self.mToFieldLabel = QtGui.QLabel(EventLayerDialogBase)
        self.mToFieldLabel.setObjectName(_fromUtf8("mToFieldLabel"))
        self.gridLayout_3.addWidget(self.mToFieldLabel, 6, 0, 1, 1)
        self.mToFieldComboBox = QtGui.QComboBox(EventLayerDialogBase)
        self.mToFieldComboBox.setObjectName(_fromUtf8("mToFieldComboBox"))
        self.gridLayout_3.addWidget(self.mToFieldComboBox, 6, 1, 1, 1)
        self.mOffsetGroupBox = QtGui.QGroupBox(EventLayerDialogBase)
        self.mOffsetGroupBox.setObjectName(_fromUtf8("mOffsetGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.mOffsetGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mOffsetFieldLabel = QtGui.QLabel(self.mOffsetGroupBox)
        self.mOffsetFieldLabel.setObjectName(_fromUtf8("mOffsetFieldLabel"))
        self.gridLayout_2.addWidget(self.mOffsetFieldLabel, 0, 0, 1, 1)
        self.mOffsetFieldComboBox = QtGui.QComboBox(self.mOffsetGroupBox)
        self.mOffsetFieldComboBox.setObjectName(_fromUtf8("mOffsetFieldComboBox"))
        self.gridLayout_2.addWidget(self.mOffsetFieldComboBox, 0, 1, 1, 1)
        self.mOffsetScaleLabel = QtGui.QLabel(self.mOffsetGroupBox)
        self.mOffsetScaleLabel.setObjectName(_fromUtf8("mOffsetScaleLabel"))
        self.gridLayout_2.addWidget(self.mOffsetScaleLabel, 1, 0, 1, 1)
        self.mOffsetScaleSpinBox = QtGui.QDoubleSpinBox(self.mOffsetGroupBox)
        self.mOffsetScaleSpinBox.setMinimum(-9999999.99)
        self.mOffsetScaleSpinBox.setMaximum(99999999.99)
        self.mOffsetScaleSpinBox.setProperty(_fromUtf8("value"), 1.0)
        self.mOffsetScaleSpinBox.setObjectName(_fromUtf8("mOffsetScaleSpinBox"))
        self.gridLayout_2.addWidget(self.mOffsetScaleSpinBox, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.mOffsetGroupBox, 7, 0, 1, 2)
        self.mOutputGroupBox = QtGui.QGroupBox(EventLayerDialogBase)
        self.mOutputGroupBox.setObjectName(_fromUtf8("mOutputGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.mOutputGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mOutputNameLabel = QtGui.QLabel(self.mOutputGroupBox)
        self.mOutputNameLabel.setObjectName(_fromUtf8("mOutputNameLabel"))
        self.gridLayout.addWidget(self.mOutputNameLabel, 0, 0, 1, 1)
        self.mOutputLayerNameEdit = QtGui.QLineEdit(self.mOutputGroupBox)
        self.mOutputLayerNameEdit.setObjectName(_fromUtf8("mOutputLayerNameEdit"))
        self.gridLayout.addWidget(self.mOutputLayerNameEdit, 0, 1, 1, 1)
        self.mForceSingleTypeCheckBox = QtGui.QCheckBox(self.mOutputGroupBox)
        self.mForceSingleTypeCheckBox.setObjectName(_fromUtf8("mForceSingleTypeCheckBox"))
        self.gridLayout.addWidget(self.mForceSingleTypeCheckBox, 2, 0, 1, 2)
        self.btnRefresh = QtGui.QPushButton(self.mOutputGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRefresh.sizePolicy().hasHeightForWidth())
        self.btnRefresh.setSizePolicy(sizePolicy)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.gridLayout.addWidget(self.btnRefresh, 3, 0, 1, 2)
        self.gridLayout_3.addWidget(self.mOutputGroupBox, 8, 0, 1, 2)
        self.btnOK = QtGui.QPushButton(EventLayerDialogBase)
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.gridLayout_3.addWidget(self.btnOK, 9, 0, 1, 1)
        self.btnCancel = QtGui.QPushButton(EventLayerDialogBase)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout_3.addWidget(self.btnCancel, 9, 1, 1, 1)

        self.retranslateUi(EventLayerDialogBase)
        QtCore.QMetaObject.connectSlotsByName(EventLayerDialogBase)

    def retranslateUi(self, EventLayerDialogBase):
        EventLayerDialogBase.setWindowTitle(QtGui.QApplication.translate("EventLayerDialogBase", "Add event layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mPointRadioButton.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineRadioButton.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineLayeLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Line layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineFieldLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Line field", None, QtGui.QApplication.UnicodeUTF8))
        self.mEventLayerLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Event layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mEventFieldLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Event field", None, QtGui.QApplication.UnicodeUTF8))
        self.mFromFieldLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.mToFieldLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.mOffsetGroupBox.setTitle(QtGui.QApplication.translate("EventLayerDialogBase", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.mOffsetFieldLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Offset field", None, QtGui.QApplication.UnicodeUTF8))
        self.mOffsetScaleLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Offset scale", None, QtGui.QApplication.UnicodeUTF8))
        self.mOutputGroupBox.setTitle(QtGui.QApplication.translate("EventLayerDialogBase", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.mOutputNameLabel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Output name", None, QtGui.QApplication.UnicodeUTF8))
        self.mForceSingleTypeCheckBox.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Force single type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("EventLayerDialogBase", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("EventLayerDialogBase", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

